# Generated by Django 2.0.5 on 2018-05-29 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('myclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('reason_in_school', models.CharField(max_length=100)),
                ('reason_out_school', models.CharField(max_length=100)),
                ('return_time', models.CharField(max_length=20)),
                ('tell', models.CharField(max_length=11)),
                ('connect', models.CharField(max_length=5)),
                ('another_tell', models.CharField(max_length=11)),
                ('fudaoyuan', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
