# Generated by Django 2.0.5 on 2018-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('-date',), 'verbose_name': '零汇报', 'verbose_name_plural': '零汇报'},
        ),
        migrations.AlterField(
            model_name='form',
            name='reason_in_school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='reason_out_school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='return_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
